services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx/default-init.conf:/etc/nginx/conf.d/default.conf:ro

  certbot:
     image: certbot/certbot
     restart: "no"
     volumes:
       - ./deploy/certbot/conf:/etc/letsencrypt
       - ./deploy/certbot/www:/var/www/certbot
     command: >
      certonly 
      --webroot 
      --webroot-path=/var/www/certbot 
      --email ${SITE_ADMIN_EMAIL} 
      --agree-tos 
      --no-eff-email 
      -d ${SITE_DOMAIN}
      --keep-until-expiring
      --non-interactive
     depends_on:
      - nginx
