name: chatmap-main

services:
  chatmap-ui:
    image: ghcr.io/hotosm/chatmap-ui:latest
    expose:
      - "80"
    environment:
      - NODE_ENV=production
    networks:
      - appnet

  chatmap-api:
    image: ghcr.io/hotosm/chatmap-api:latest
    ports:
      - "8000:8000"
    depends_on:
      - chatmap-redis
    environment:
      - REDIS_HOST=chatmap-redis
      - REDIS_PORT=6379
      - SERVER_URL=http://chatmap-go:8001
      # - CHATMAP_ENC_KEY=
      # - CHATMAP_SECRET_KEY=
    volumes:
      - ./media:/app/media
      - ./data:/app/data
    networks:
      - appnet

  chatmap-go:
    image: ghcr.io/hotosm/chatmap-im-connector:latest
    environment:
      - REDIS_HOST=chatmap-redis
      - REDIS_PORT=6379
      # - CHATMAP_ENC_KEY=
    ports:
      - "8001:8001"
    volumes:
      - ./sessions:/app/sessions
    networks:
      - appnet

  chatmap-redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - appnet

  # chatmap-certbot:
  #    image: certbot/certbot:latest
  #    command: renew --quiet
  #    volumes:
  #      - ./letsencrypt:/etc/letsencrypt
  #    depends_on:
  #      - chatmap-nginx

  chatmap-nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - chatmap-ui
    networks:
      - appnet

networks:
  appnet: