"""Initial migration

Revision ID: 0001
Revises: 
Create Date: 2026-03-01 04:05:12.911543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sharing', sa.Enum('private', 'public', name='sharing_permission'), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', name='uq_maps_owner_id'),
    )
    
    op.create_table('points',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('map_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    )
    
    op.create_index('ix_points_map_id', 'points', ['map_id'], unique=False)
    op.create_index('ix_points_username', 'points', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_points_username', table_name='points')
    op.drop_index('ix_points_map_id', table_name='points')
    op.drop_table('points')
    op.drop_table('maps')
    # ### end Alembic commands ###