"""empty message

Revision ID: 6d6a20ec27e1
Revises: 78016e58ae19
Create Date: 2026-03-08 15:44:43.615858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d6a20ec27e1'
down_revision: Union[str, Sequence[str], None] = '78016e58ae19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maps', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.add_column('maps', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maps', 'updated_at')
    op.drop_column('maps', 'created_at')
    # ### end Alembic commands ###
