"""empty message

Revision ID: 78016e58ae19
Revises: 5d7e8452f39a
Create Date: 2026-03-04 20:01:23.972241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78016e58ae19'
down_revision: Union[str, Sequence[str], None] = '5d7e8452f39a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_maps_owner_id', 'maps', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_maps_owner_id", "maps", ["owner_id"])
    # ### end Alembic commands ###
