"""empty message

Revision ID: d79ca9eeda4b
Revises: 6d6a20ec27e1
Create Date: 2026-03-19 17:11:54.926806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd79ca9eeda4b'
down_revision: Union[str, Sequence[str], None] = '6d6a20ec27e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points', 'tags')
    # ### end Alembic commands ###
