# ChatMap Web UI - Development Dockerfile
# Build context: HOT/ (parent directory)

FROM node:22-alpine3.21 AS development

WORKDIR /app

RUN npm install -g npm@11.5.2
RUN npm install -g --force yarn

# Copy chatmap-ui package files
# Note: @hotosm/hanko-auth is now installed from npm, not local auth-libs
COPY chatmap/chatmap-ui/package*.json chatmap/chatmap-ui/yarn.lock ./

RUN yarn install

# Copy chatmap-ui source
COPY chatmap/chatmap-ui/ .

EXPOSE 5173

CMD ["yarn", "start", "--host", "0.0.0.0"]
