name: Build and publish images

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push chatmap-ui
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./chatmap-ui/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/chatmap-ui:latest

      - name: Build and push chatmap-im-connector
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./chatmap-im-connector/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/chatmap-im-connector:latest

      - name: Build and push chatmap-api
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./chatmap-api/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/chatmap-api:latest
